spring:
  profiles:
    active: dev

---
# 开发环境
spring:
  application:
    name: abcmsc-config-dev
  profiles: dev

---

# 测试环境 spring:
spring:
    application:
      name: abcmsc-config-test
    profiles: test

